# PDF Builder — HTML template + weasyprint PDF rendering

import markdown2


PDF_CSS = """
@page {
    size: letter;
    margin: 1in;
    @bottom-right { content: "Page " counter(page) " of " counter(pages); font-size: 9px; color: #666; }
}
body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11pt; line-height: 1.6; color: #1a1a1a; }
h1 { font-size: 22pt; color: #1e3a5f; border-bottom: 2px solid #1e3a5f; padding-bottom: 8px; margin-top: 30px; }
h2 { font-size: 16pt; color: #2563eb; margin-top: 24px; }
h3 { font-size: 13pt; color: #334155; margin-top: 18px; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; }
th, td { border: 1px solid #cbd5e1; padding: 6px 10px; text-align: left; font-size: 10pt; }
th { background-color: #f1f5f9; font-weight: 600; }
.cover { text-align: center; padding-top: 200px; page-break-after: always; }
.cover h1 { font-size: 28pt; border: none; color: #1e3a5f; }
.cover p { font-size: 12pt; color: #64748b; margin: 8px 0; }
.section { page-break-before: always; }
.severity-critical { color: #dc2626; font-weight: 600; }
.severity-warning { color: #d97706; font-weight: 600; }
.severity-info { color: #2563eb; }
ul, ol { padding-left: 24px; }
blockquote { border-left: 3px solid #2563eb; padding-left: 12px; margin: 12px 0; color: #475569; }
"""


def render_pdf(html_content: str) -> bytes:
    """Render HTML string to PDF bytes using weasyprint."""
    try:
        from weasyprint import HTML
        return HTML(string=html_content).write_pdf()
    except ImportError:
        # Fallback: return HTML as bytes if weasyprint not installed
        return html_content.encode("utf-8")


def build_appeal_html(sections: dict, metadata: dict) -> str:
    """Build a full HTML document from appeal packet sections with cover page."""
    cover = f"""
    <div class="cover">
        <h1>Medical Billing Dispute Packet</h1>
        <p><strong>Patient:</strong> [Patient Name]</p>
        <p><strong>Provider:</strong> {metadata.get('provider', '[Provider]')}</p>
        <p><strong>Facility:</strong> {metadata.get('facility', '[Facility]')}</p>
        <p><strong>Service Date:</strong> {metadata.get('service_date_range', {}).get('start', '[Date]')}</p>
        <p><strong>Account #:</strong> [Account Number]</p>
        <p style="margin-top: 40px; font-size: 10pt; color: #94a3b8;">
            Generated by BillClarity Appeals Engine
        </p>
    </div>
    """

    section_titles = {
        "bill_explanation": "Bill Explanation Report",
        "flagged_issues": "Flagged Issues Summary",
        "benchmark_analysis": "Benchmark Comparison Analysis",
        "insurance_insights": "Insurance Rule Insights",
        "appeal_letter": "Formal Appeal Letter",
        "coding_review_request": "Coding Review Request",
        "negotiation_script": "Negotiation Script",
        "evidence_checklist": "Evidence Checklist",
    }

    # Table of contents
    toc = '<div class="section"><h1>Table of Contents</h1><ol>'
    for key in sections:
        title = section_titles.get(key, key.replace("_", " ").title())
        toc += f"<li>{title}</li>"
    toc += "</ol></div>"

    # Sections
    body_sections = ""
    for key, content in sections.items():
        title = section_titles.get(key, key.replace("_", " ").title())
        if isinstance(content, list):
            # Evidence checklist comes as a list
            html_content = "<ul>" + "".join(f"<li>{item}</li>" for item in content) + "</ul>"
        elif isinstance(content, str):
            html_content = markdown2.markdown(
                content, extras=["tables", "fenced-code-blocks", "break-on-newline"]
            )
        else:
            html_content = str(content)

        body_sections += f'<div class="section"><h1>{title}</h1>{html_content}</div>'

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>{PDF_CSS}</style></head>
<body>
{cover}
{toc}
{body_sections}
</body>
</html>"""

    return html
