version = 0.1

[default.deploy.parameters]
stack_name = "billclarity-stack"
resolve_s3 = true
s3_prefix = "billclarity-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" S3BucketName=\"billclarity-docs-891377296503\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
